-- Baseline schema for PostgreSQL/SQLite migration tooling.
-- Runtime initialization uses SQLAlchemy metadata; Alembic can adopt this
-- baseline with `alembic stamp head` and subsequent revisions.
CREATE TABLE users (id INTEGER PRIMARY KEY, username VARCHAR(40) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'user', is_active BOOLEAN NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE projects (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, name VARCHAR(120) NOT NULL, description VARCHAR(500) NOT NULL DEFAULT '', primary_language VARCHAR(30) NOT NULL DEFAULT 'python', is_favorite BOOLEAN NOT NULL DEFAULT 0, is_public BOOLEAN NOT NULL DEFAULT 0, share_token VARCHAR(64) UNIQUE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE project_files (id INTEGER PRIMARY KEY, project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE, filename VARCHAR(255) NOT NULL, language VARCHAR(30) NOT NULL, content TEXT NOT NULL DEFAULT '', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE(project_id, filename));
CREATE TABLE project_versions (id INTEGER PRIMARY KEY, project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE, file_id INTEGER NOT NULL REFERENCES project_files(id) ON DELETE CASCADE, content TEXT NOT NULL, version_number INTEGER NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE executions (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL, language VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL, stdout TEXT NOT NULL DEFAULT '', stderr TEXT NOT NULL DEFAULT '', execution_time FLOAT, memory_usage FLOAT, created_at TIMESTAMP NOT NULL);
CREATE TABLE ai_requests (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL, request_type VARCHAR(30) NOT NULL, prompt TEXT NOT NULL, created_at TIMESTAMP NOT NULL);
